runtime: java21 
env: standard

instance_class: F1 

handlers:
  - url: /.*
    script: auto  

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"