runtime: java21 
env: standard

instance_class: F1 

handlers:
  - url: /.*
    script: auto  

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  basic:
    auth:
      username: "69bd2211a05e151338291eb88add1fcdd30966b4d92a1de7f3fb651f3e5078db"
      password: "a38a93d531f47f114f2daf20814566dff658615eb2dc20f2d813b95fc5746160"

  external:
    api:
      auth:
        token: "TEST-8880838102327336-032800-217e4c4d52a6061af92f91ab09754f1b-2354988343"

  jwt:
    secret: "WG4ycjV1OHgvQT9EKEcrS2JQZVNoVmtZcDNzNnY5eSQ="